name: binbuddy_backend
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  shelf:

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
